### PR TITLE
Allow whitespace in arguments to 'callback' option

### PR DESCRIPTION
**Pull request by lemzwerg**

### CODE REVIEW

**Comment by Josef-Friedrich** [comment]
Thank you very much!

**Comment by Josef-Friedrich** [comment]
I would like to manage options with luakeys in the hopefully not too distant future: https://www.ctan.org/pkg/luakeys.

**Comment by lemzwerg** [comment]
OK.  However, I won't work on that :slightly_smiling_face:

**Comment by Josef-Friedrich** [comment]
It was not meant like that. I would work on the switch to luakeys myself.

**Comment by lemzwerg** [comment]
Alles klar.  You've missed my smiley :slightly_smiling_face:

**Pull request merged**
