### PR TITLE
CSS and HTML fixes

### PR DESCRIPTION
**Pull request by lemzwerg**

### CODE REVIEW

**Comment by lemzwerg** [comment]
I suggest to not squash the three commits into a single one for better readability.

**Comment by Josef-Friedrich** [comment]
Thank you very much!

**Comment by lemzwerg** [comment]
You are welcome!  Just curious: Was the commit squashing intentional?

**Comment by Josef-Friedrich** [comment]
Sorry I read your comment too quickly ... I thought I should squash

**Pull request merged**
