### PR TITLE
Callbacks

### PR DESCRIPTION
**Pull request by lemzwerg**
Here is my fix.

Note that your latest formatting changes create warnings with both `luacheck` and `ldoc` that weren't present before...

### CODE REVIEW

**Comment by Josef-Friedrich** [comment]
Thank you for pointing this out and thank you for the PR.

**Comment by Josef-Friedrich** [comment]
`make test` produces several errors on my side

for example

`lualatex tests/lualatex/callbacks/vpack.tex`

Screenshot from 2023-08-09 16-07-35

**Comment by lemzwerg** [comment]
Uh, oh, sorry.  Will check this soon.

**Comment by lemzwerg** [comment]
See #39.

**Pull request merged**
